import { StyleSheet } from 'react-native';
import type { AppTheme } from '../../constants/themes';
import { palette } from '../../constants/colors';

export function createStyles(
  colors: AppTheme['colors'],
  spacing: AppTheme['spacing'],
  radius: AppTheme['radius'],
  headerBg: string,
  headerBgLight: string,
  decorBg: string,
) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      paddingTop: 56,
      paddingBottom: 28,
      paddingHorizontal: 24,
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      backgroundColor: headerBg,
      overflow: 'hidden',
    },
    decor1: {
      position: 'absolute',
      top: -40,
      right: -30,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: decorBg,
    },
    decor2: {
      position: 'absolute',
      bottom: 10,
      left: -50,
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: decorBg,
    },
    decor3: {
      position: 'absolute',
      top: 30,
      right: 80,
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: decorBg,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    backBtn: {
      width: 40,
      height: 40,
      backgroundColor: 'rgba(255,255,255,0.2)',
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    backBtnText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '600',
    },
    topTitle: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '700',
    },
    topSpacer: {
      width: 40,
    },
    headerBody: {
      alignItems: 'center',
      marginTop: 20,
    },
    stepLabel: {
      color: 'rgba(255,255,255,0.7)',
      fontSize: 13,
      fontWeight: '500',
    },
    stepStepper: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      marginTop: 18,
    },
    stepConnector: {
      flex: 1,
      height: 2,
      borderRadius: 1,
      backgroundColor: 'rgba(255,255,255,0.22)',
      marginHorizontal: 4,
    },
    stepConnectorActive: {
      backgroundColor: '#FFFFFF',
    },
    stepDot: {
      width: 27,
      height: 27,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    stepDotDone: {
      backgroundColor: '#FFFFFF',
    },
    stepDotCurrent: {
      backgroundColor: '#FFFFFF',
      borderWidth: 3,
      borderColor: palette.primary,
      transform: [{ scale: 1.12 }],
    },
    stepDotPending: {
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
    currentStepName: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
      marginTop: 14,
    },
    currentStepCount: {
      fontSize: 12,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.7)',
    },
    progressBar: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 10,
      gap: 6,
    },
    progressDot: {
      height: 6,
      borderRadius: 3,
    },
    progressDotActive: {
      backgroundColor: '#FFFFFF',
      width: 40,
    },
    progressDotInactive: {
      backgroundColor: 'rgba(255,255,255,0.25)',
      width: 12,
    },
    flex: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 20,
    },
    contentPadding: {
      paddingHorizontal: spacing.lg,
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 10,
      marginTop: spacing.xl,
      color: colors.textSecondary,
    },
    loanGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    loanGridEmpty: {
      width: '100%',
      textAlign: 'center',
      color: colors.textSecondary,
    },
    loadingWrap: {
      alignItems: 'center',
      paddingVertical: 32,
    },
    loanCard: {
      width: '47%',
      borderWidth: 1.5,
      padding: 16,
      alignItems: 'center',
      overflow: 'hidden',
      borderRadius: radius.lg,
    },
    loanCardSelected: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    loanCardUnselected: {
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    loanCardPressed: {
      backgroundColor: headerBgLight,
    },
    loanIconWrap: {
      width: 52,
      height: 52,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
    },
    loanIcon: {
      fontSize: 26,
    },
    loanLabel: {
      fontSize: 14,
      fontWeight: '700',
      textAlign: 'center',
    },
    loanRange: {
      fontSize: 11,
      fontWeight: '500',
      marginTop: 3,
    },
    nearestCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      padding: 16,
      marginVertical: 8,
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
      borderRadius: radius.lg,
    },
    nearestIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.primary + '1A',
      marginRight: 12,
    },
    nearestBody: {
      flex: 1,
    },
    nearestLabel: {
      fontSize: 11,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      color: colors.textSecondary,
    },
    nearestName: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      marginTop: 2,
    },
    nearestMeta: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
      marginTop: 2,
    },
    nearestDistance: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.primary,
      marginLeft: 10,
    },
    nearestLoading: {
      alignItems: 'center',
      paddingVertical: 14,
    },
    nearestCoords: {
      borderWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginVertical: 8,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: radius.md,
    },
    nearestCoordRow: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
      marginBottom: 4,
    },
    nearestCoordValue: {
      fontWeight: '700',
      color: colors.text,
    },
    branchSearch: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      borderRadius: radius.lg,
      paddingHorizontal: 14,
      marginBottom: 12,
      gap: 8,
    },
    branchSearchInput: {
      flex: 1,
      fontSize: 14,
      paddingVertical: 12,
      color: colors.text,
    },
    branchFallbackHint: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.warning,
      marginBottom: 10,
    },
    branchLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: radius.md,
      backgroundColor: colors.primary + '0D',
      marginBottom: 12,
      //   width: '100',
      //   flex: 1,
      //   justifyContent: 'center',
    },
    branchLocationText: {
      flex: 1,
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    branchLocationValue: {
      fontWeight: '700',
      color: colors.text,
    },
    branchDebugBox: {
      borderWidth: 1,
      borderStyle: 'dashed',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: radius.md,
      marginBottom: 12,
      borderColor: colors.info + '55',
      backgroundColor: colors.surface,
    },
    branchDebugTitle: {
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      color: colors.textSecondary,
      marginBottom: 6,
    },
    branchDebugHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    branchDebugMapBtn: {
      width: 28,
      height: 28,
      borderRadius: 9,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'flex-end',
      backgroundColor: colors.primary + '14',
      marginBottom: 4,
    },
    branchDebugRow: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
      marginTop: 2,
    },
    branchDebugValue: {
      fontWeight: '700',
      color: colors.text,
    },
    branchDebugValueWarn: {
      color: colors.warning,
    },
    branchDebugValueOk: {
      color: colors.success,
    },
    currentAddressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 12,
    },
    currentAddressText: {
      flex: 1,
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
      color: colors.textSecondary,
    },
    branchLoading: {
      alignItems: 'center',
      paddingVertical: 32,
    },
    branchList: {
      gap: 10,
    },
    branchListEmpty: {
      textAlign: 'center',
      paddingVertical: 24,
    },
    branchCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      padding: 14,
      borderRadius: radius.lg,
    },
    branchCardSelected: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    branchCardUnselected: {
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    branchCardPressed: {
      backgroundColor: headerBgLight,
    },
    branchIconWrap: {
      width: 42,
      height: 42,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.primary + '1A',
      marginRight: 12,
    },
    branchIconWrapSelected: {
      backgroundColor: 'rgba(255,255,255,0.2)',
    },
    branchInfo: {
      flex: 1,
    },
    branchNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    branchName: {
      fontSize: 15,
      fontWeight: '700',
    },
    branchNearestChip: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: colors.success + '20',
    },
    branchNearestChipText: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.success,
    },
    branchMeta: {
      fontSize: 12,
      fontWeight: '500',
      marginTop: 2,
    },
    branchPhoneRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 4,
    },
    branchRight: {
      alignItems: 'flex-end',
      gap: 4,
      marginLeft: 8,
    },
    branchDistance: {
      fontSize: 13,
      fontWeight: '700',
    },
    branchMapBtn: {
      width: 28,
      height: 28,
      borderRadius: 9,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 2,
    },
    branchMapBtnSelected: {
      backgroundColor: 'rgba(255,255,255,0.22)',
    },
    branchMapBtnUnselected: {
      backgroundColor: colors.primary + '14',
    },
    cardTick: {
      position: 'absolute',
      top: 6,
      right: 6,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    cardTickText: {
      fontSize: 9,
      fontWeight: '800',
      color: colors.primary,
    },
    inputCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 4,
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
      borderRadius: radius.lg,
    },
    inputPrefix: {
      fontSize: 18,
      fontWeight: '700',
      marginRight: 8,
      color: colors.textSecondary,
    },
    amountHero: {
      borderWidth: 1.5,
      padding: 18,
      borderRadius: radius.lg,
      backgroundColor: '#F59E0B' + '0D',
      borderColor: '#F59E0B' + '40',
    },
    amountHeroError: {
      borderColor: colors.error + '66',
    },
    amountHeroHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    amountHeroLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    amountHeroIcon: {
      width: 32,
      height: 32,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
    },
    amountHeroLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    amountClear: {
      width: 26,
      height: 26,
      borderRadius: 13,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
    },
    amountInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 12,
    },
    amountPrefix: {
      fontSize: 30,
      fontWeight: '800',
      color: '#F59E0B',
      marginRight: 6,
    },
    amountInput: {
      flex: 1,
      minWidth: 0,
      fontSize: 34,
      fontWeight: '800',
      color: colors.text,
      paddingVertical: 0,
      paddingHorizontal: 0,
    },
    amountError: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.error,
      marginTop: 6,
    },
    quickAmountWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 14,
    },
    quickAmountChip: {
      borderWidth: 1.5,
      paddingVertical: 8,
      paddingHorizontal: 14,
      overflow: 'hidden',
      borderRadius: radius.pill,
    },
    quickAmountChipSelected: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    quickAmountChipUnselected: {
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    quickAmountChipPressed: {
      backgroundColor: headerBgLight,
    },
    quickAmountChipText: {
      fontSize: 12,
      fontWeight: '700',
    },
    quickAmountChipTextSelected: {
      color: '#FFFFFF',
    },
    quickAmountChipTextUnselected: {
      color: colors.textSecondary,
    },
    tenureSec: {
      marginTop: 22,
    },
    tenureLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: 10,
    },
    tenureRow: {
      flexDirection: 'row',
      gap: 10,
    },
    tenureChip: {
      flex: 1,
      borderWidth: 1.5,
      paddingVertical: 12,
      overflow: 'hidden',
      borderRadius: radius.lg,
      alignItems: 'center',
    },
    tenureChipSelected: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    tenureChipUnselected: {
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    tenureChipPressed: {
      backgroundColor: headerBgLight,
    },
    tenureChipValue: {
      fontSize: 17,
      fontWeight: '800',
    },
    tenureChipValueSelected: {
      color: '#FFFFFF',
    },
    tenureChipValueUnselected: {
      color: colors.text,
    },
    tenureChipUnit: {
      fontSize: 10,
      fontWeight: '600',
      marginTop: 1,
    },
    tenureChipUnitSelected: {
      color: 'rgba(255,255,255,0.8)',
    },
    tenureChipUnitUnselected: {
      color: colors.textSecondary,
    },
    purposeEditorCard: {
      borderWidth: 1.5,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceElevated,
      borderColor: '#8B5CF6' + '55',
      marginTop: 22,
      overflow: 'hidden',
    },
    purposeEditorHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: '#8B5CF6' + '0F',
    },
    purposeEditorTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    purposeEditorCount: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    purposeEditorInput: {
      minHeight: 140,
      fontSize: 15,
      lineHeight: 22,
      color: colors.text,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 14,
    },
    purposeEditorFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
    },
    purposeEditorHint: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    input: {
      flex: 1,
      fontSize: 17,
      fontWeight: '600',
      paddingVertical: 14,
      color: colors.text,
    },
    chipTickSmall: {
      position: 'absolute',
      top: 3,
      right: 3,
      width: 14,
      height: 14,
      borderRadius: 8,
      backgroundColor: '#FFFFFF',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    chipTickTextSmall: {
      fontSize: 9,
      fontWeight: '800',
      color: colors.primary,
    },
    employmentRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    incomeHeroCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      padding: 16,
      borderRadius: radius.lg,
      marginBottom: 8,
      backgroundColor: '#10B981' + '0D',
      borderColor: '#10B981' + '2E',
    },
    incomeHeroIcon: {
      width: 46,
      height: 46,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      marginRight: 12,
    },
    incomeHeroBody: {
      flex: 1,
    },
    incomeHeroTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    incomeHeroText: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
      color: colors.textSecondary,
      marginTop: 2,
    },
    employmentSec: {
      marginTop: 20,
    },
    employmentLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: 10,
    },
    employmentGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    employmentOptCard: {
      width: '48%',
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1.5,
      padding: 14,
      overflow: 'hidden',
      borderRadius: radius.lg,
    },
    employmentOptCardSelected: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    employmentOptCardUnselected: {
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    employmentOptCardPressed: {
      backgroundColor: headerBgLight,
    },
    employmentOptIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.primary + '1A',
      marginRight: 10,
    },
    employmentOptIconSelected: {
      backgroundColor: 'rgba(255,255,255,0.2)',
    },
    employmentOptLabel: {
      flex: 1,
      fontSize: 13,
      fontWeight: '700',
      marginRight: 4,
    },
    employmentOptLabelSelected: {
      color: '#FFFFFF',
    },
    employmentOptLabelUnselected: {
      color: colors.text,
    },
    employmentOptTick: {
      marginLeft: 4,
    },
    employmentError: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.error,
      marginTop: 8,
    },
    referenceFormCard: {
      borderWidth: 1,
      padding: 16,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    referenceNoteRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 14,
    },
    referenceNoteText: {
      flex: 1,
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    refWrap: {
      gap: 14,
    },
    refEntryCard: {
      borderWidth: 1,
      padding: 16,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    refEntryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 14,
    },
    refEntryBadge: {
      width: 26,
      height: 26,
      borderRadius: 13,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: palette.primary,
      marginRight: 10,
    },
    refEntryBadgeText: {
      fontSize: 12,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    refEntryTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    refEntryRemove: {
      width: 30,
      height: 30,
      borderRadius: 15,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.error + '12',
    },
    refTypeLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
      marginBottom: 8,
    },
    refTypeRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    refTypeChip: {
      borderWidth: 1.5,
      paddingVertical: 8,
      paddingHorizontal: 14,
      overflow: 'hidden',
      borderRadius: radius.pill,
    },
    refTypeChipSelected: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    refTypeChipUnselected: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    refTypeChipPressed: {
      backgroundColor: headerBgLight,
    },
    refTypeChipText: {
      fontSize: 12,
      fontWeight: '600',
    },
    refTypeChipTextSelected: {
      color: '#FFFFFF',
    },
    refTypeChipTextUnselected: {
      color: colors.textSecondary,
    },
    refEntryError: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.error,
      marginTop: 6,
    },
    refEntryNote: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 10,
      padding: 10,
      borderRadius: radius.md,
      backgroundColor: colors.surface,
    },
    refEntryNoteText: {
      flex: 1,
      fontSize: 11,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    refAddBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      paddingVertical: 14,
      borderRadius: radius.lg,
      borderColor: colors.primary + '66',
      backgroundColor: colors.primary + '08',
    },
    refAddBtnText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.primary,
    },
    refSummaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    refSummaryText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    employmentChip: {
      borderWidth: 1.5,
      paddingVertical: 12,
      paddingHorizontal: 20,
      overflow: 'hidden',
      borderRadius: radius.md,
    },
    employmentChipSelected: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    employmentChipUnselected: {
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
    },
    employmentChipPressed: {
      backgroundColor: headerBgLight,
    },
    employmentText: {
      fontSize: 14,
      fontWeight: '600',
    },
    summaryCard: {
      borderWidth: 1,
      padding: 20,
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
      borderRadius: radius.lg,
      marginTop: spacing.xl,
    },
    summaryTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    summaryDivider: {
      height: 1,
      marginVertical: 14,
      backgroundColor: colors.border,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    summaryLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    summaryValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    summarySection: {
      borderWidth: 1,
      padding: 16,
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.border,
      borderRadius: radius.lg,
      marginBottom: 12,
    },
    summarySectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 12,
    },
    summarySectionIcon: {
      width: 36,
      height: 36,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    summarySectionIconRed: {
      width: 36,
      height: 36,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#EF4444' + '14',
    },
    summarySectionTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
    },
    summarySectionRows: {
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 12,
      gap: 8,
    },
    summarySectionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
    },
    summarySectionRowLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    summarySectionLabel: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    summarySectionValue: {
      flexShrink: 1,
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
      textAlign: 'right',
    },
    summarySectionValueMuted: {
      fontWeight: '500',
      color: colors.textSecondary,
    },
    summarySectionValueStrong: {
      fontWeight: '800',
      color: colors.text,
    },
    reviewHero: {
      borderWidth: 1,
      padding: 20,
      borderRadius: radius.lg,
      marginBottom: 12,
      backgroundColor: palette.primary + '0D',
      borderColor: palette.primary + '2E',
    },
    reviewHeroHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    reviewHeroLabel: {
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      color: colors.textSecondary,
    },
    reviewHeroBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: colors.surfaceElevated,
    },
    reviewHeroBadgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: palette.primary,
    },
    reviewHeroAmount: {
      fontSize: 34,
      fontWeight: '800',
      color: colors.text,
      marginTop: 8,
    },
    reviewHeroDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 16,
    },
    reviewHeroStats: {
      flexDirection: 'row',
    },
    reviewHeroStat: {
      flex: 1,
    },
    reviewHeroStatMid: {
      borderLeftWidth: 1,
      borderColor: colors.border,
      paddingLeft: 14,
    },
    reviewHeroStatLabel: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    reviewHeroStatValue: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
      marginTop: 2,
    },
    reviewHeroPurpose: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginTop: 14,
      paddingTop: 14,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    reviewHeroPurposeLabel: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    reviewHeroPurposeValue: {
      flex: 1,
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    docList: {
      gap: 10,
      marginTop: 14,
    },
    docRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      padding: 12,
      borderRadius: radius.md,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    docRowIcon: {
      marginRight: 10,
    },
    docRowInfo: {
      flex: 1,
    },
    docRowLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    docRowFile: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
      marginTop: 1,
    },
    docEyeBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.primary + '14',
      marginLeft: 10,
    },
    docChipEmpty: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    referenceCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      padding: 16,
      borderRadius: radius.lg,
      marginBottom: 16,
      backgroundColor: colors.primary + '0D',
      borderColor: colors.primary + '2E',
    },
    referenceCardIcon: {
      width: 46,
      height: 46,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      marginRight: 12,
    },
    referenceCardBody: {
      flex: 1,
    },
    referenceCardTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    referenceCardText: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 17,
      color: colors.textSecondary,
      marginTop: 2,
    },
    bottomSpacer: {
      height: 40,
    },
    docWrap: {
      gap: 12,
    },
    docProgressCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      padding: 16,
      borderRadius: radius.lg,
      backgroundColor: colors.primary + '0D',
      borderColor: colors.primary + '33',
      marginBottom: 4,
    },
    docProgressCardComplete: {
      backgroundColor: colors.success + '12',
      borderColor: colors.success + '40',
    },
    docProgressIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      marginRight: 12,
    },
    docProgressInfo: {
      flex: 1,
    },
    docProgressTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    docProgressMeta: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
      marginTop: 2,
    },
    docProgressTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.border,
      marginTop: 10,
      overflow: 'hidden',
    },
    docProgressFill: {
      height: '100%',
      borderRadius: 3,
      backgroundColor: colors.primary,
    },
    docProgressFillComplete: {
      backgroundColor: colors.success,
    },
    docCard: {
      borderWidth: 1.5,
      padding: 14,
      borderRadius: radius.lg,
      backgroundColor: colors.surfaceElevated,
    },
    docCardEmpty: {
      borderColor: colors.primary + '40',
      borderStyle: 'dashed',
    },
    docCardUploaded: {
      borderColor: colors.success + '55',
      flexDirection: 'row',
      alignItems: 'center',
    },
    docCardBody: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    docIconWrap: {
      width: 46,
      height: 46,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      marginRight: 12,
    },
    docThumb: {
      width: 46,
      height: 46,
    },
    docInfo: {
      flex: 1,
      minWidth: 0,
    },
    docNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    docName: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.text,
      flexShrink: 1,
    },
    docTagRequired: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: colors.warning + '20',
    },
    docTagRequiredText: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.warning,
    },
    docTagUploaded: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 999,
      backgroundColor: colors.success + '20',
    },
    docTagUploadedText: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.success,
    },
    docMeta: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textSecondary,
      marginTop: 2,
      flexShrink: 1,
    },
    docActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 4,
    },
    docAction: {
      fontSize: 12,
      fontWeight: '700',
    },
    docRemoveBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.error + '12',
      marginLeft: 10,
    },
    docActions: {
      gap: 8,
      marginLeft: 10,
      alignItems: 'center',
    },
    docError: {
      fontSize: 13,
      fontWeight: '500',
      color: colors.error,
      marginTop: 2,
    },
    footer: {
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.surface,
    },
    nextBtn: {
      alignItems: 'center',
      paddingVertical: 16,
      borderRadius: radius.pill,
    },
    nextBtnEnabled: {
      backgroundColor: palette.primary,
    },
    nextBtnDisabled: {
      backgroundColor: colors.border,
    },
    nextBtnText: {
      fontSize: 16,
      fontWeight: '700',
    },
  });
}
