import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      flex: 1,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      marginLeft: 4,
    },
    headerSpacer: {
      width: 36,
    },
    separator: {
      height: 0.5,
      backgroundColor: colors.border,
    },
    hero: {
      backgroundColor: colors.primary,
      borderRadius: 20,
      padding: 20,
      marginHorizontal: 16,
      marginTop: 16,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },
    heroDecor1: {
      position: 'absolute',
      top: -50,
      right: -30,
      width: 140,
      height: 140,
      borderRadius: 70,
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
    heroDecor2: {
      position: 'absolute',
      bottom: -40,
      left: -20,
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: 'rgba(255,255,255,0.06)',
    },
    heroTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    heroTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: 'rgba(255,255,255,0.9)',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    paidBadge: {
      backgroundColor: '#22C55E',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
    },
    paidText: {
      fontSize: 10,
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: 0.5,
    },
    emiLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.85)',
      marginTop: 14,
    },
    emiAmount: {
      fontSize: 34,
      fontWeight: '800',
      color: '#FFFFFF',
      marginTop: 2,
    },
    heroDivider: {
      height: 1,
      backgroundColor: 'rgba(255,255,255,0.18)',
      marginVertical: 14,
    },
    heroRow: {
      flexDirection: 'row',
    },
    heroCol: {
      flex: 1,
    },
    heroColLabel: {
      fontSize: 9,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      color: 'rgba(255,255,255,0.7)',
    },
    heroColValue: {
      fontSize: 13,
      fontWeight: '700',
      color: '#FFFFFF',
      marginTop: 2,
    },
    statsRow: {
      flexDirection: 'row',
      gap: 12,
      marginHorizontal: 16,
      marginTop: 16,
    },
    statCard: {
      flex: 1,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 14,
      alignItems: 'center',
    },
    statLabel: {
      fontSize: 10,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.3,
      color: colors.textSecondary,
    },
    statValue: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
      marginTop: 4,
    },
    statValueSuccess: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.success,
      marginTop: 4,
    },
    section: {
      paddingHorizontal: 16,
      marginTop: 22,
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
    },
    sectionSub: {
      fontSize: 12,
      color: colors.textSecondary,
      marginTop: 2,
    },
    borrowingCard: {
      flexDirection: 'row',
      backgroundColor: colors.surfaceElevated,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 18,
      paddingHorizontal: 16,
      alignItems: 'center',
      marginTop: 12,
    },
    borrowingItem: {
      flex: 1,
    },
    dot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      marginBottom: 6,
    },
    borrowingLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    borrowingValue: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.text,
      marginTop: 2,
    },
    borrowingDivider: {
      width: 1,
      height: 36,
      backgroundColor: colors.border,
      marginHorizontal: 16,
    },
    overviewCard: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginHorizontal: 16,
      marginTop: 12,
      overflow: 'hidden',
    },
    overviewRow: {
      flexDirection: 'row',
    },
    overviewCell: {
      flex: 1,
      padding: 14,
    },
    cellDividerRight: {
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: colors.border,
    },
    rowDivider: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    cellLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    cellValue: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.text,
      marginTop: 3,
    },
    scheduleList: {
      paddingHorizontal: 16,
      gap: 12,
      marginTop: 12,
    },
    chartLoader: {
      marginTop: 12,
      marginHorizontal: 16,
      paddingVertical: 32,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      gap: 10,
    },
    emptyWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 72,
      paddingHorizontal: 32,
      gap: 10,
    },
    emptyIcon: {
      fontSize: 40,
    },
    emptyTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.text,
    },
    emptySub: {
      fontSize: 13,
      lineHeight: 20,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 6,
    },
    chartLoaderText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    chartErrorText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.warning,
      textAlign: 'center',
    },
    retryBtn: {
      backgroundColor: colors.primary,
      borderRadius: 10,
      paddingHorizontal: 22,
      paddingVertical: 10,
    },
    retryText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
    },
    estimatedNote: {
      marginTop: 12,
      marginHorizontal: 16,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderRadius: 10,
      backgroundColor: colors.warning + '18',
    },
    estimatedNoteText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.warning,
      textAlign: 'center',
    },
    downloadBtn: {
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
      marginTop: 24,
      marginHorizontal: 16,
    },
    downloadText: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '800',
    },
    footer: {
      paddingTop: 4,
      paddingBottom: 40,
    },
  });

export type AmortizationStyles = ReturnType<typeof createStyles>;